/**
 * List of fields that can be used to query torrents
 */
const fields = [
  'id',
  'addedDate',
  'creator',
  'doneDate',
  'comment',
  'name',
  'totalSize',
  'error',
  'errorString',
  'eta',
  'etaIdle',
  'isFinished',
  'isStalled',
  'isPrivate',
  'files',
  'fileStats',
  'hashString',
  'leftUntilDone',
  'metadataPercentComplete',
  'peers',
  'peersFrom',
  'peersConnected',
  'peersGettingFromUs',
  'peersSendingToUs',
  'percentDone',
  'queuePosition',
  'rateDownload',
  'rateUpload',
  'secondsDownloading',
  'secondsSeeding',
  'recheckProgress',
  'seedRatioMode',
  'seedRatioLimit',
  'seedIdleLimit',
  'sizeWhenDone',
  'status',
  'trackers',
  'downloadDir',
  'downloadLimit',
  'downloadLimited',
  'uploadedEver',
  'downloadedEver',
  'corruptEver',
  'uploadRatio',
  'webseedsSendingToUs',
  'haveUnchecked',
  'haveValid',
  'honorsSessionLimits',
  'manualAnnounceTime',
  'activityDate',
  'desiredAvailable',
  'labels',
  'magnetLink',
  'maxConnectedPeers',
  'peer-limit',
  'priorities',
  'wanted',
  'webseeds',
];

/**
 * Status codes mapped to their string representation
 * @see https://github.com/transmission/transmission/blob/main/docs/rpc-spec.md#33-torrent-accessor-torrent-get
 */
const Status = {
  0: 'STOPPED',
  1: 'QUEUED_CHECK',
  2: 'CHECKING',
  3: 'QUEUED_DOWNLOAD',
  4: 'DOWNLOADING',
  5: 'QUEUED_SEED',
  6: 'SEEDING',
} as const;

export { fields, Status };
