name: Make Release

on:
  workflow_dispatch: {}

concurrency:
  group: on-release-publish

permissions: {}

jobs:
  publish-npm:
    environment: npm
    # Needed as recommended by npm docs on publishing with provenance https://docs.npmjs.com/generating-provenance-statements
    permissions:
      id-token: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Setup auth tokens
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          npm set "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}"
      - name: Setup Node and dependencies
        uses: ./.github/actions/cached-node
        with:
          build: true
      - name: Bump version
        run: npx standard-version
      - name: Push changelog and tags
        run: git push --follow-tags origin HEAD:main
      - name: Publish to npm
        run: npm publish --provenance --access public
